[book]
authors = ["zhangs"]
language = "en"
multilingual = false
src = "src"
title = "编程笔记"


# 配置项说明：https://hellowac.github.io/mdbook-doc-zh/zh-cn/format/configuration/renderers.html
[output.html]
default-theme = "rust"
preferred-dark-theme = "light"
curly-quotes = false
mathjax-support = false
no-section-label = true
git-repository-url = "https://github.com/ZhSMM/blog"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/ZhSMM/blog/edit/main/{path}"
site-url = "/"
cname = "blog.268574.xyz"
additional-js = ["mermaid.min.js", "mermaid-init.js", "theme/pagetoc.js"]
additional-css = ["theme/pagetoc.css"]

[output.html.playground]
editable = true
copy-js = true
line-numbers = true

[output.html.fold]
enable = true

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3
copy-js = true

# 启用 mdbook-katex 预处理器（核心）
# https://github.com/jontze/mdbook-katex
[preprocessor.katex]
renderers = ["html"]
macros = "macros.txt"
# 启用katex预处理
enable = true
# 允许行内公式（$...$），默认开启
allow-inline = true
# 允许块级公式（$$...$$），默认开启
allow-block = true
# 自动为块级公式生成编号（如 (1.1)），按需开启
auto-number = true
# 公式编号格式（{chapter}.{section}.{equation}）
number-format = "{chapter}.{section}.{equation}"
# 加载 KaTeX 扩展（如支持化学公式、流程图，按需添加）
extensions = ["katex-mhchem", "tikz"]  # mhchem 支持化学公式（如 \ce{H2O}），tikz 支持简单绘图

[preprocessor.pagetoc]

# https://github.com/badboy/mdbook-toc
[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
marker = "* auto-gen TOC;\n{:toc}"
max-level = 4

[preprocessor.mermaid]
command = "mdbook-mermaid"